services:
  endpoint:
    image: node:18
    command: sh -c "npm i && npm run db:migrate && npm run seed:run && npm run start:dev"
    container_name: sisgha-endpoint
    restart: always
    working_dir: /code
    depends_on:
      - endpoint-db
      - endpoint-meilisearch
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/code
    networks:
      - sisgha-net

  endpoint-db:
    image: bitnami/postgresql:15
    container_name: sisgha-endpoint-db
    restart: always
    volumes:
      - 'sisgha-endpoint-db-data:/bitnami/postgresql'
      - './volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    env_file:
      - .db.env
    networks:
      - sisgha-net
    ports:
      - 5191:5432

  endpoint-meilisearch:
    image: getmeili/meilisearch:v1.0.2
    container_name: sisgha-endpoint-meilisearch
    restart: always
    env_file:
      - .meilisearch.env
    volumes:
      - 'sisgha-endpoint-meilisearch-data:/data.ms'
    networks:
      - sisgha-net


networks:
  sisgha-net:

volumes:
  sisgha-endpoint-db-data:
  sisgha-endpoint-meilisearch-data:
